### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [waldronmatt/musicWebTemplate#17]
Greetings @waldronmatt  ,

I'm a Graphic Designer and I've reached you believing that a logo proposal would be helpful to this project!
A good logo that transmit a message its helpful when it comes to publicity, making it appealing to the eye.
If this is something of your interest, we can get started towards the logo-making process.

I'll be looking forward for your reply
Best Regards,
-Luigi.

**Comment by waldronmatt** [comment]
Hey LuigiBaute,

I think that's a great idea! I haven't given much thought yet to a logo, but am very much interested. I'm going to close this for now and I'll reopen when I'm ready to collaborate.

Thanks for reaching out.

Best,

- Matt

**Comment by LuigiBaute** [comment]
Great @waldronmatt !

Whenever you're ready to start, we should get in touch to start as soon as posible.

Best regards.

**Comment by waldronmatt** [comment]
Hi Luigi, apologies for the wait. I'm ready to collaborate on a logo. Can you send a few logo designs incorporating a silhouette of someone holding a microphone and the git project title? Open to other ideas as well.
