### ISSUE TITLE
Help: Requesting Logo for Project

### ISSUE THREAD

**Issue by waldronmatt** [waldronmatt/musicWebTemplate#21]
Requesting help from someone with graphic design experience to create a logo that matches the theme and personality of the music template. 

Looking for a minimalist logo (using project key words/acronyms) with contrasting colors and accenting shapes. Open to other ideas.

**Comment by mirzazulfan** [comment]
Hi @waldronmatt , What about this?
![mwt](https://user-images.githubusercontent.com/36124339/50507636-e68c7f80-0ab0-11e9-8eb1-46166a19087d.png)

**Comment by mirzazulfan** [comment]
Thanks for your response @waldronmatt ,, like this ? if you need to change please let me know.
![v2](https://user-images.githubusercontent.com/36124339/50544749-077cde00-0c33-11e9-8cef-f9594afa38ab.png)

**Comment by waldronmatt** [comment]
Thanks @mirzazulfan these look really good! I think these will be ready to advertise. 

Can you please send the png/jpeg files of the blue/purple **top and bottom** logos under **1** and the white themed logos (**1st and 2nd screenshot**)?

**Comment by mirzazulfan** [comment]
Hi @waldronmatt , You can download all files and editables in [Gdrive](https://drive.google.com/drive/folders/10CywDny3V6MdQsGDwOw2Ttg8xPT-w_pm?ogsrc=32) . 
I made it 2 versions. Thanks for accepting my proposal. PR #22

Best regard.

**Comment by waldronmatt** [comment]
Fantastic! Thank you again.
